/**
 * Types for Workflow Execution Popup
 *
 * These TypeScript interfaces define the contract between the renderer process
 * and the main process for the workflow execution popup feature.
 *
 * Feature: 010-workflow-execution-popup
 */

// ============================================================================
// Core Data Types
// ============================================================================

/**
 * Reference to a selected file
 */
export interface FileReference {
  id: string;
  path: string;
  name: string;
  size: number;
  mimeType: string;
  selectedAt: string; // ISO8601
}

/**
 * Reference to a file generated by workflow
 */
export interface OutputFileReference {
  path: string;
  name: string;
  size: number;
  mimeType: string;
}

/**
 * Configuration for an input field
 */
export interface InputFieldConfig {
  nodeId: string;
  nodeType: 'promptInput' | 'fileSelector';
  nodeName: string;
  value: string | FileReference[];
  required: boolean;
}

/**
 * Output from a ResultDisplay node
 */
export interface OutputResult {
  nodeId: string;
  nodeName: string;
  contentType: 'markdown' | 'text' | 'file';
  content: string;
  fileReference: OutputFileReference | null;
}

/**
 * Result from a workflow execution
 */
export interface ExecutionResult {
  executionId: string;
  status: 'success' | 'error' | 'timeout';
  startedAt: string; // ISO8601
  completedAt: string; // ISO8601
  durationMs: number;
  outputs: OutputResult[];
  error: string | null;
}

/**
 * Complete popup configuration for a workflow
 */
export interface WorkflowPopupConfig {
  workflowId: string;
  workflowName: string;
  lastUpdated: string; // ISO8601
  inputs: Record<string, InputFieldConfig>;
  lastExecution: ExecutionResult | null;
}

// ============================================================================
// IPC Request/Response Types
// ============================================================================

/**
 * Workflow node information for analysis
 */
export interface WorkflowNodeInfo {
  nodeId: string;
  nodeName: string;
  nodeType: string;
  parameters: Record<string, unknown>;
}

/**
 * Result of workflow analysis
 */
export interface WorkflowAnalysisResult {
  workflowId: string;
  workflowName: string;
  promptInputNodes: WorkflowNodeInfo[];
  fileSelectorNodes: WorkflowNodeInfo[];
  resultDisplayNodes: WorkflowNodeInfo[];
  isSupported: boolean;
  error?: string;
}

/**
 * Request to execute a workflow
 */
export interface ExecuteWorkflowRequest {
  workflowId: string;
  inputs: Record<string, InputFieldConfig>;
  timeout?: number; // milliseconds, default 300000 (5 min)
}

/**
 * Response from workflow execution start
 */
export interface ExecuteWorkflowResponse {
  success: boolean;
  executionId?: string;
  error?: string;
}

/**
 * Status of an ongoing execution
 */
export interface ExecutionStatusResponse {
  executionId: string;
  status: 'running' | 'success' | 'error' | 'waiting';
  progress?: number; // 0-100
  result?: ExecutionResult;
}

/**
 * File selection dialog options
 */
export interface FileSelectOptions {
  title?: string;
  filters?: Array<{ name: string; extensions: string[] }>;
  defaultPath?: string;
  multiSelect?: boolean;
}

/**
 * File selection dialog result
 */
export interface FileSelectResult {
  cancelled: boolean;
  filePaths: string[];
  files: FileReference[];
}

/**
 * File save dialog options
 */
export interface FileSaveOptions {
  title?: string;
  defaultPath?: string;
  filters?: Array<{ name: string; extensions: string[] }>;
}

/**
 * File save dialog result
 */
export interface FileSaveResult {
  cancelled: boolean;
  filePath?: string;
}

// ============================================================================
// Preload API Type (exposed to renderer)
// ============================================================================

/**
 * API exposed to renderer via contextBridge
 *
 * Usage in renderer:
 *   const result = await window.electron.workflowPopup.analyze('workflow-id');
 */
export interface WorkflowPopupAPI {
  analyze: (workflowId: string) => Promise<WorkflowAnalysisResult>;
  getConfig: (workflowId: string) => Promise<WorkflowPopupConfig | null>;
  saveConfig: (config: WorkflowPopupConfig) => Promise<{ success: boolean }>;
  deleteConfig: (workflowId: string) => Promise<{ success: boolean }>;
  execute: (request: ExecuteWorkflowRequest) => Promise<ExecuteWorkflowResponse>;
  status: (executionId: string) => Promise<ExecutionStatusResponse>;
  cancel: (executionId: string) => Promise<{ success: boolean }>;
  selectFiles: (options: FileSelectOptions) => Promise<FileSelectResult>;
  saveFile: (options: FileSaveOptions) => Promise<FileSaveResult>;
  copyOutputFile: (
    sourcePath: string,
    destinationPath: string
  ) => Promise<{ success: boolean; error?: string }>;
}

// ============================================================================
// Electron Bridge HTTP API (for n8n nodes)
// ============================================================================

/**
 * HTTP endpoints exposed by Electron bridge for n8n custom nodes
 * Base URL: process.env.ELECTRON_BRIDGE_URL (default http://127.0.0.1:5680)
 */
export interface ElectronBridgeWorkflowAPI {
  /**
   * GET /api/electron-bridge/execution-config/:executionId/:nodeId
   *
   * Retrieve external input config for a node during execution
   * Called by custom n8n nodes to get popup-provided values
   */
  getExecutionConfig: {
    params: { executionId: string; nodeId: string };
    response: {
      success: boolean;
      hasExternalConfig: boolean;
      config?: {
        nodeType: 'promptInput' | 'fileSelector';
        value: string | FileReference[];
      };
    };
  };

  /**
   * POST /api/electron-bridge/execution-config
   *
   * Store execution config before starting workflow
   * Called by main process before triggering n8n execution
   */
  setExecutionConfig: {
    body: {
      executionId: string;
      configs: Record<
        string,
        {
          nodeId: string;
          nodeType: 'promptInput' | 'fileSelector';
          value: string | FileReference[];
        }
      >;
    };
    response: { success: boolean };
  };

  /**
   * DELETE /api/electron-bridge/execution-config/:executionId
   *
   * Clean up execution config after workflow completes
   */
  deleteExecutionConfig: {
    params: { executionId: string };
    response: { success: boolean };
  };

  /**
   * POST /api/electron-bridge/execution-result
   *
   * Store result from ResultDisplay node during execution
   * Called by ResultDisplay node to emit output for popup
   */
  storeExecutionResult: {
    body: {
      executionId: string;
      nodeId: string;
      result: OutputResult;
    };
    response: { success: boolean };
  };

  /**
   * GET /api/electron-bridge/execution-results/:executionId
   *
   * Retrieve all stored results for an execution
   * Called by main process after workflow completes
   */
  getExecutionResults: {
    params: { executionId: string };
    response: {
      success: boolean;
      results: OutputResult[];
    };
  };
}
